spring:
  application:
    name: kafka-producer
  main:
    banner-mode: off
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.apache.kafka: off

server:
  port: 8080
