spring:
  application:
    name: kafka-producer
  main:
    banner-mode: off
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
#      retries: 10 # явно лучше не указывать
      properties:
#        retry:
#          backoff:
#            ms: 1000 # явно лучше не указывать
        delivery:
          timeout:
            ms: 60000 # лучше указать
        linger:
          ms: 0
        request:
          timeout:
            ms: 10000

logging:
  level:
    org.apache.kafka: off

server:
  port: 8080
